### ISSUE TITLE
有几个错误

### ISSUE THREAD

**Issue by Sum41forever** [z-android/ZLayer#1]
com.zlayer.net.ZRequestParams.java

```
public void putFile(String attr, File file, String mimeType) {
    if (attr != null && file != null) {
    mFileParams.put(attr);  //这个地方少个;  号
    }
}
```

并且编译通不过
D:\Workspaces\ZLayer-master\zlayer\src\main\java\prin\com\zlayer\net\ZRequestParams.java
Error:(25, 20) 错误: 对于put(String), 找不到合适的方法
方法 AbstractMap.put(String,Object)不适用
(实际参数列表和形式参数列表长度不同)
方法 ConcurrentHashMap.put(String,Object)不适用
(实际参数列表和形式参数列表长度不同)

**Comment by z-android** [comment]
嗯嗯   目前是代码直播版本    还未发布   正式出来的会是搭配个使用demo并且经过测试的健壮lib，实时同步主要是想吸纳更多人的意见，并且更多人参与进来一起去开发这个lib库  谢谢你的发现！
